name: Trigger Tardis LFS Cache

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]


jobs:
  trigger-tardis-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger LFS Cache Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/tardis-sn/tardis/actions/workflows/lfs-cache.yml/dispatches \
            -d '{
              "ref": "master",
              "inputs": {
                "atom-data-sparse": "false",
                "allow_lfs_pull": "true"
              }
            }' 
      - name: Trigger LFS Cache Workflow Atom Data Sparse
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/tardis-sn/tardis/actions/workflows/lfs-cache.yml/dispatches \
          -d '{
            "ref": "master",
            "inputs": {
              "atom-data-sparse": "true",
              "allow_lfs_pull": "true"
            }
          }' 
